//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_MSSQL_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableB
    {
        public int B_Id { get; set; }
        public string B_Like { get; set; }
        public string A_Id { get; set; }
        public int TableAA_Id { get; set; }
    
        public virtual TableA TableA { get; set; }
    }
}
